### ISSUE TITLE
Can not install species anymore

### ISSUE THREAD

**Issue by nnekaede** [openvax/pyensembl#204]
I previously ran this line of code in a jupyter notebook and it worked:
`! pyensembl install --release 75 76 --species human`

Now I get the following error:

```
2018-07-20 21:12:15,713 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=75, species='homo_sapiens')
2018-07-20 21:12:15,713 - pyensembl.download_cache - INFO - Fetching /root/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz from URL ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz
2018-07-20 21:12:15,713 - datacache.download - INFO - Downloading ftp://ftp.ensembl.org/pub/release-75/gtf/homo_sapiens/Homo_sapiens.GRCh37.75.gtf.gz to /root/.cache/pyensembl/GRCh37/ensembl75/Homo_sapiens.GRCh37.75.gtf.gz
Traceback (most recent call last):
  File "/opt/conda/bin/pyensembl", line 11, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/shell.py", line 195, in run
    genome.download(overwrite=args.overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/genome.py", line 276, in download
    self._set_local_paths(download_if_missing=True, overwrite=overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/genome.py", line 234, in _set_local_paths
    overwrite=overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/genome.py", line 198, in _get_gtf_path
    overwrite=overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/genome.py", line 191, in _get_cached_path
    overwrite=overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/download_cache.py", line 299, in local_path_or_install_error
    overwrite=overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/download_cache.py", line 274, in download_or_copy_if_necessary
    overwrite)
  File "/opt/conda/lib/python3.6/site-packages/pyensembl/download_cache.py", line 222, in _download_if_necessary
    timeout=3600)
  File "/opt/conda/lib/python3.6/site-packages/datacache/download.py", line 106, in _download_and_decompress_if_necessary
    use_wget_if_available=use_wget_if_available)
  File "/opt/conda/lib/python3.6/site-packages/datacache/download.py", line 79, in _download_to_temp_file
    logger.info("Running: %s" % (" ".join(wget_command_list)))
TypeError: sequence item 6: expected str instance, int found
```

Can you please inform me on what I am doing wrong.

**Comment by iskandr** [comment]
Hi @nnekaede -- sorry about that. I think you caught me in the middle of trying to fix Travis. 

Can you try updating both `pyensembl` and `datacache` and then try again?

**Comment by nnekaede** [comment]
Thank you so much! It works again.
