### ISSUE TITLE
$ pyensembl install --species mouse --release 93 error

### ISSUE THREAD

**Issue by AhmedArslan** [openvax/pyensembl#218]
**Trying to install pyensembl database (mouse) on my ssh server (python3) and need help with the following error:**

2019-02-04 11:50:44,821 - datacache.database_helpers - WARNING - Failed to create tables ['start_codon', 'exon', 'gene', 'stop_codon', 'CDS', 'transcript'] in database /home/aarslan/.cache/pyensembl/GRCm38/ensembl93/Mus_musculus.GRCm38.93.gtf.db
Traceback (most recent call last):
  File "/usr/bin/pyensembl", line 11, in <module>
    load_entry_point('pyensembl==1.7.3', 'console_scripts', 'pyensembl')()
  File "/usr/lib/python3.4/site-packages/pyensembl/shell.py", line 261, in run
    genome.index(overwrite=args.overwrite)
  File "/usr/lib/python3.4/site-packages/pyensembl/genome.py", line 280, in index
    self.db.connect_or_create(overwrite=overwrite)
  File "/usr/lib/python3.4/site-packages/pyensembl/database.py", line 293, in connect_or_create
    return self.create(overwrite=overwrite)
  File "/usr/lib/python3.4/site-packages/pyensembl/database.py", line 253, in create
    version=DATABASE_SCHEMA_VERSION)
  File "/usr/lib/python3.4/site-packages/datacache/database_helpers.py", line 183, in db_from_dataframes_with_absolute_path
    version=version)
  File "/usr/lib/python3.4/site-packages/datacache/database_helpers.py", line 102, in _create_cached_db
    db.create(tables, version)
  File "/usr/lib/python3.4/site-packages/datacache/database.py", line 183, in create
    self._fill_table(table.name, table.rows)
  File "/usr/lib/python3.4/site-packages/datacache/database.py", line 164, in _fill_table
    self.connection.executemany(sql, rows)
sqlite3.OperationalError: disk I/O error

**Comment by fabianegli** [comment]
From the distance, looking at `sqlite3.OperationalError: disk I/O error` it looks like there might not be enough disk space available in `/home/aarslan/.cache/pyensembl/GRCm38/ensembl93/` where the `Mus_musculus.GRCm38.93.gtf.db` is written - or there are permission problems, e.g. [Backup/Sync processes](https://stackoverflow.com/q/47540607) or ["Do not use SQLite with a networked file system." (because sqlite locks dbs - only one process can access it at a time)](https://www.mail-archive.com/sqlite-users@mailinglists.sqlite.org/msg64432.html), that can arise from a multitude of sources and would require more information from your side to troubleshoot.

**Comment by iskandr** [comment]
Agree with @fabianegli -- going to close this issue but will reopen if @AhmedArslan can add more info.
