### ISSUE TITLE
Can't install v2.2.2 using pip -> requirements.txt missing

### ISSUE THREAD

**Issue by Cloufield** [openvax/pyensembl#274]
Hi, 
Thanks a lot for your wonderful package! 
I am trying to update to the latest version but it seems that the  'requirements.txt' file is missing? 
(which seems to be changed in the last commit)

```
pip install pyensembl==2.2.2
...

Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bm/8twyqzpn187fhqq_p7b1_zrm0000gn/T/pip-install-dq_nkzey/pyensembl/setup.py", line 44, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by iskandr** [comment]
Oof, sorry about that, I guess need to add it to the package data.

I'll fix it a little later today.

**Comment by iskandr** [comment]
Fixed by https://github.com/openvax/pyensembl/pull/275
