### ISSUE TITLE
sqlite bug

### ISSUE THREAD

**Issue by hermanzhaozzzz** [openvax/pyensembl#284]
can not be used in a lusture system...

**Comment by iskandr** [comment]
Can you describe the error more? What message do you get? And what is your
system configuration?

**Comment by hermanzhaozzzz** [comment]
Hi, thanks for your reply.

Platform (Ubuntu with lustre disk system)

Error

```shell
(base) ➜  ~ pyensembl install --release 77 --species homo_sapiens

2023-02-22 22:18:29,278 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=77, species='homo_sapiens')
Traceback (most recent call last):
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/bin/pyensembl", line 10, in <module>
    sys.exit(run())
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/pyensembl/shell.py", line 256, in run
    genome.index(overwrite=args.overwrite)
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/pyensembl/genome.py", line 275, in index
    self.db.connect_or_create(overwrite=overwrite)
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/pyensembl/database.py", line 287, in connect_or_create
    connection = self._get_connection()
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/pyensembl/database.py", line 263, in _get_connection
    self._connection = datacache.connect_if_correct_version(
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/datacache/database_helpers.py", line 47, in connect_if_correct_version
    if db.has_version() and db.version() == version:
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/datacache/database.py", line 83, in has_version
    return self.has_table(METADATA_TABLE_NAME)
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/datacache/database.py", line 57, in has_table
    table_names = self.table_names()
  File "/lustre1/chengqiyi_pkuhpc/zhaohn/0.apps/miniconda3/lib/python3.10/site-packages/datacache/database.py", line 51, in table_names
    cursor = self.connection.execute(query)
sqlite3.OperationalError: disk I/O error
```

I think it might be a sqlite error, since there is a same error from ipython kernel as follow:

```shell
(base) ➜  ~ ipython
[TerminalIPythonApp] ERROR | Failed to open SQLite history /lustre1/chengqiyi_pkuhpc/zhaohn/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | History file was moved to /lustre1/chengqiyi_pkuhpc/zhaohn/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /lustre1/chengqiyi_pkuhpc/zhaohn/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | History file was moved to /lustre1/chengqiyi_pkuhpc/zhaohn/.ipython/profile_default/history-corrupt.sqlite and a new file created.
[TerminalIPythonApp] ERROR | Failed to open SQLite history /lustre1/chengqiyi_pkuhpc/zhaohn/.ipython/profile_default/history.sqlite (disk I/O error).
[TerminalIPythonApp] ERROR | Failed to load history too many times, history will not be saved.
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]:
```

**Comment by hermanzhaozzzz** [comment]
I can write or read on this lustre system, and the disk quota is enough to write. 
It seems that lustre system does not support sqlite3...
