### ISSUE TITLE
Error installing: "Failed to find sqlite3 column type for category"

### ISSUE THREAD

**Issue by pjlaw** [openvax/pyensembl#312]
I'm trying to install an Ensembl release

`pyensembl install --release 105 --species human`

But I get the following error:
```
2024-11-04 15:59:58,643 - pyensembl.shell - INFO - Running 'install' for EnsemblRelease(release=105, species='homo_sapiens')
2024-11-04 15:59:58,643 - pyensembl.database - INFO - Creating database: /home/plaw/.cache/pyensembl/GRCh38/ensembl105/Homo_sapiens.GRCh38.105.gtf.db
2024-11-04 15:59:58,643 - pyensembl.database - INFO - Reading GTF from /home/plaw/.cache/pyensembl/GRCh38/ensembl105/Homo_sapiens.GRCh38.105.gtf.gz
Traceback (most recent call last):
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/bin/pyensembl", line 10, in <module>
    sys.exit(run())
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/pyensembl/shell.py", line 281, in run
    genome.index(overwrite=args.overwrite)
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/pyensembl/genome.py", line 280, in index
    self.db.connect_or_create(overwrite=overwrite)
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/pyensembl/database.py", line 286, in connect_or_create
    return self.create(overwrite=overwrite)
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/pyensembl/database.py", line 239, in create
    self._connection = datacache.db_from_dataframes_with_absolute_path(
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/datacache/database_helpers.py", line 176, in db_from_dataframes_with_absolute_path
    tables = build_tables(
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/datacache/database_helpers.py", line 136, in build_tables
    table = DatabaseTable.from_dataframe(
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/datacache/database_table.py", line 56, in from_dataframe
    column_db_type = db_type(values.dtype)
  File "/data/scratch/DGE/DUDGE/MOPOPGEN/plaw/conda_envs/EagleC/lib/python3.8/site-packages/datacache/database_types.py", line 96, in db_type
    raise ValueError("Failed to find sqlite3 column type for %s" % (
ValueError: Failed to find sqlite3 column type for category
```

I've tried to install different Ensemble releases, with the same result. Using pyensembl 2.3.13

**Comment by pjlaw** [comment]
Managed to resolve this. When I created my conda environment, it installed datacache 1.1.5, which is very old. I updated it to the latest version (1.4.1) and managed to successfully create the Ensembl database

`pip install datacache --upgrade`
